// ⚠️ SECURITY WARNING: This file allows local development since .env.local is gitignored and blocked.
// TODO: Move these to proper Vercel Environment Variables before deploying.

export const NEXT_PUBLIC_SUPABASE_URL = "https://eafkcvwshcedsilumphy.supabase.co"
export const NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZmtjdndzaGNlZHNpbHVtcGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MTM1OTQsImV4cCI6MjA4MDE4OTU5NH0.WqZw_5kDvTmDhyldZhhEhWdjhbsnVQ6gpBW_Gy2ZyoA"
export const SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZmtjdndzaGNlZHNpbHVtcGh5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDYxMzU5NCwiZXhwIjoyMDgwMTg5NTk0fQ.Mhx1yX3TD2SoNqudNfC48oGVBImIZrY1VFILOpRKF4g"
